//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlEditorTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlEditorTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../Resources/ComponentToSrcFileMap.csv.
        /// </summary>
        internal static string ComponentToSourceFileMap {
            get {
                return ResourceManager.GetString("ComponentToSourceFileMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component,SourceFile
        ///AnimationComponent,EngineAnimationComponent.h
        ///AudioComponent,EngineAudioComponent.h
        ///Action,Action.h
        ///.
        /// </summary>
        internal static string ComponentToSrcFileMap {
            get {
                return ResourceManager.GetString("ComponentToSrcFileMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro,Datatype,NumDefaultArgs,StartIndex,Header1,Header2,Header3,Header4
        ///PIPELINE_ANGLE,float,1,1,Angle,,,
        ///PIPELINE_ANGLE_REQUIRED,float,1,1,Angle,,,
        ///PIPELINE_BASICSTRING,string,1,1,StringValue,,,
        ///PIPELINE_BASICSTRING_REQUIRED,string,1,1,StringValue,,,
        ///PIPELINE_BASICSTRING_SIZE,string,1,1,StringValue,,,
        ///PIPELINE_BOOL,boolean,1,1,BooleanValue,,,
        ///PIPELINE_BOOL_REQUIRED,boolean,1,1,BooleanValue,,,
        ///PIPELINE_CHARACTER,string,1,1,Character,,,
        ///PIPELINE_CHARACTER_REQUIRED,string,1,1,Character,,,
        ///PIPELINE_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MacroDatatypeCsv {
            get {
                return ResourceManager.GetString("MacroDatatypeCsv", resourceCulture);
            }
        }
    }
}
